import 'dart:io';
import 'dart:typed_data';

import 'package:file_picker/file_picker.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../../features/labs/presentation/models/lab_entry_models.dart';

class PdfReportService {
  Future<String?> generateMedicalReport({
    required bool isAr,
    required int score,
    required int waterAmount,
    required int waterGoal,
    required int greenTeaCount,
    required int teaGoal,
    required bool chkVitD,
    required bool walk30,
    required bool sun15,
    required bool lowFatDay,
    required List<LabEntry> labs,
  }) async {
    final now = DateTime.now();
    final date = now.toIso8601String().split('T').first;

    final pdf = pw.Document();
    final checklistDone = [chkVitD, walk30, sun15, lowFatDay]
        .where((v) => v)
        .length;

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(24),
        build: (context) {
          return [
            pw.Text(
              isAr ? 'Medical Summary Report' : 'Medical Summary Report',
              style: pw.TextStyle(
                fontSize: 20,
                fontWeight: pw.FontWeight.bold,
              ),
            ),
            pw.SizedBox(height: 4),
            pw.Text(
              'Itmain - $date',
              style: const pw.TextStyle(fontSize: 11),
            ),
            pw.SizedBox(height: 16),
            pw.Container(
              padding: const pw.EdgeInsets.all(12),
              decoration: pw.BoxDecoration(
                border: pw.Border.all(color: PdfColors.grey400),
                borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
              ),
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(
                    'Daily Dashboard',
                    style: pw.TextStyle(
                      fontSize: 13,
                      fontWeight: pw.FontWeight.bold,
                    ),
                  ),
                  pw.SizedBox(height: 6),
                  pw.Text('Overall Score: $score%'),
                  pw.Text('Hydration: $waterAmount / $waterGoal mL'),
                  pw.Text('Green Tea: $greenTeaCount / $teaGoal cups'),
                  pw.Text('Checklist Done: $checklistDone / 4'),
                ],
              ),
            ),
            pw.SizedBox(height: 14),
            pw.Text(
              'Lab Results',
              style: pw.TextStyle(
                fontSize: 13,
                fontWeight: pw.FontWeight.bold,
              ),
            ),
            pw.SizedBox(height: 8),
            if (labs.isEmpty)
              pw.Container(
                width: double.infinity,
                padding: const pw.EdgeInsets.all(12),
                decoration: pw.BoxDecoration(
                  border: pw.Border.all(color: PdfColors.grey400),
                ),
                child: pw.Text('No lab records yet.'),
              )
            else
              pw.TableHelper.fromTextArray(
                headerDecoration: const pw.BoxDecoration(
                  color: PdfColors.blueGrey100,
                ),
                headerStyle: pw.TextStyle(
                  fontWeight: pw.FontWeight.bold,
                  fontSize: 10,
                ),
                cellStyle: const pw.TextStyle(fontSize: 9),
                cellAlignments: {
                  0: pw.Alignment.centerLeft,
                  1: pw.Alignment.center,
                  2: pw.Alignment.center,
                  3: pw.Alignment.center,
                  4: pw.Alignment.center,
                },
                headers: const ['Metric', 'Value', 'Ref Range', 'Status', 'Date'],
                data: labs
                    .map(
                      (lab) => [
                        lab.metric,
                        '${lab.value} ${lab.unit}'.trim(),
                        lab.refRange,
                        lab.status,
                        lab.date,
                      ],
                    )
                    .toList(),
              ),
            pw.SizedBox(height: 16),
            pw.Text(
              'Generated by Itmain',
              style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700),
            ),
          ];
        },
      ),
    );

    final bytes = await pdf.save();
    final fileName = 'itmain_report_$date.pdf';
    return _savePdfBytes(bytes, fileName);
  }

  Future<String?> _savePdfBytes(Uint8List bytes, String fileName) async {
    if (Platform.isAndroid || Platform.isIOS) {
      final dir = await getTemporaryDirectory();
      final outputPath = p.join(dir.path, fileName);
      await File(outputPath).writeAsBytes(bytes, flush: true);
      return outputPath;
    }

    final selectedPath = await FilePicker.platform.saveFile(
      dialogTitle: 'Save PDF Report',
      fileName: fileName,
      type: FileType.custom,
      allowedExtensions: ['pdf'],
    );

    if (selectedPath == null) {
      return null;
    }

    final outputPath = selectedPath.toLowerCase().endsWith('.pdf')
        ? selectedPath
        : '$selectedPath.pdf';
    await File(outputPath).writeAsBytes(bytes, flush: true);
    return outputPath;
  }
}
